Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Solution 1:
class Solution {
public:
    char findTheDifference(string s, string t) {
        map<char,int> mp;
        char c;
        for(int i=0; i<s.size(); i++)
        {
            mp[s[i]]++;
        }
        for(int i=0;i<t.size();i++)
        {
            mp[t[i]]--;
        }
        for(int i=0;i<t.size();i++)
        {
            if(mp[t[i]]!=0)
              c = t[i];
        }
        return c;
        
    }
};

Solution-2:Do X_OR
class Solution {
public:
    char findTheDifference(string s, string t) {
      char c=0;
        for(auto i:s)
            c = c^i;
        for(auto i:t)
            c = c^i;
        return c;
        
    }
};
